//components
import Head from "next/head";
import Introduction from "../components/Introduction";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfólio | Ryan Lima</title>
        <meta name="description" content="Generated by create-next-app" />
        <link
          rel="shortcut icon"
          href="https://ymatheusvieira.vercel.app/assets/img/html2.svg"
          type="image/x-icon"
        />
      </Head>

      <Introduction />
    </>
  );
}
